#' @title Step 6: Retirement Threshold Sensitivity Analysis
#' @description This script assesses the sensitivity of workforce projections to retirement rate
#' assumptions by varying inactivity detection thresholds. It simulates the impact of shortening
#' or extending those thresholds by ±1 year.
#' @author Tyler Muffly, MD / Claude Code
#' @date 2026-01-12
#' @return CSV and image files showing the retirement threshold sensitivity analysis.
#' @seealso \code{\link{00_RUN_ALL.R}}, \code{\link{01_consolidate_workforce_data.R}}

#!/usr/bin/env Rscript
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Step 6: Retirement Threshold Sensitivity Analysis
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
# Purpose: Assess sensitivity of workforce projections to retirement rate
#          assumptions by varying inactivity detection thresholds
#
# Background: Retirement detection uses a 7-source hierarchical system with
#             time-based inactivity thresholds. This analysis simulates the
#             impact of shortening or extending those thresholds by ±1 year.
#
# Scenarios:
#   - Baseline: Current retirement rates (4.4%, 5.2%, 3.4%)
#   - Threshold -1yr: Stricter (detect more retirements, +15% rate)
#   - Threshold +1yr: Looser (detect fewer retirements, -15% rate)
#   - Conservative: Moderate adjustment (±10% rate)
#   - Aggressive: Strong adjustment (±30% rate)
#
# Author: Tyler Muffly, MD / Claude Code
# Date: 2026-01-12
#
# Usage:
#   Rscript cliff/code/06_retirement_sensitivity.R
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# The 'suppressPackageStartupMessages' function prevents package startup messages from being printed.
suppressPackageStartupMessages({
  # The 'tidyverse' library is a collection of R packages designed for data science.
  # It includes ggplot2, dplyr, tidyr, readr, purrr, and tibble.
  library(tidyverse)
  # The 'here' library helps to create reproducible paths to files.
  library(here)
  # The 'scales' library provides tools for customizing the scales of ggplot2 plots.
  library(scales)
  # The 'yaml' library is used to read YAML configuration files.
  library(yaml)
})

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Configuration
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Baseline retirement rates from validated 7-source system
# The 'tribble' function creates a tibble (a modern data frame) from data entered row-by-row.
BASELINE_RATES <- tribble(
  ~subspecialty, ~baseline_rate,
  "URPS",        0.8809,
  "GO",          1.0027,
  "MIGS",        0.7024
)

# Fellowship assumptions (use default scenario)
CONFIG_FILE <- here("config/fellowship_assumptions.yml")
# The 'read_yaml' function reads a YAML file and returns it as a list.
config <- read_yaml(CONFIG_FILE)
FELLOWSHIP_DEFAULT <- config$default

# Use consolidated data generated by Step 1 as baseline
INPUT_CSV <- here("data/workforce_projections_consolidated.csv")

# Standard deviations (from original analysis)
SD_VALUES <- tribble(
  ~subspecialty, ~sd_2029,
  "URPS",        15.2,
  "GO",          16.1,
  "MIGS",        11.0
)

cat("\n")
cat(paste0(rep("=", 80), collapse = ""), "\n")
cat("RETIREMENT THRESHOLD SENSITIVITY ANALYSIS\n")
cat(paste0(rep("=", 80), collapse = ""), "\n")
cat("\n")

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Define Retirement Rate Scenarios
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Threshold adjustment scenarios
# -1 year threshold: More retirements detected → +15% rate
# +1 year threshold: Fewer retirements detected → -15% rate

retirement_scenarios <- list(
  baseline = list(
    name = "Baseline (Current)",
    description = "Current detection thresholds",
    adjustment = 0.00
  ),
  threshold_minus_1yr = list(
    name = "Threshold -1yr (Stricter)",
    description = "Detect retirements 1 year earlier",
    adjustment = 0.15  # 15% higher retirement rate
  ),
  threshold_plus_1yr = list(
    name = "Threshold +1yr (Looser)",
    description = "Detect retirements 1 year later",
    adjustment = -0.15  # 15% lower retirement rate
  ),
  conservative_higher = list(
    name = "Conservative Higher (+10%)",
    description = "Moderately higher retirement rates",
    adjustment = 0.10
  ),
  conservative_lower = list(
    name = "Conservative Lower (-10%)",
    description = "Moderately lower retirement rates",
    adjustment = -0.10
  ),
  aggressive_higher = list(
    name = "Aggressive Higher (+30%)",
    description = "Much higher retirement rates",
    adjustment = 0.30
  ),
  aggressive_lower = list(
    name = "Aggressive Lower (-30%)",
    description = "Much lower retirement rates",
    adjustment = -0.30
  )
)

cat("Defined retirement rate scenarios:\n")
for (scenario_id in names(retirement_scenarios)) {
  sc <- retirement_scenarios[[scenario_id]]
  adj_pct <- sprintf("%+.0f%%", sc$adjustment * 100)
  cat(sprintf("  • %-30s %s\n", sc$name, adj_pct))
}
cat("\n")

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Load Baseline Data
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

cat("[", as.character(Sys.time()), "] Loading baseline data\n", sep = "")

# The 'read_csv' function reads a comma-separated value (CSV) file into a tibble.
baseline_data <- read_csv(INPUT_CSV, show_col_types = FALSE) %>%
  # The 'transmute' function is similar to 'mutate', but it drops all other variables.
  transmute(
    subspecialty_full = subspecialty,
    subspecialty = subspecialty_abbrev,
    baseline_workforce = baseline_2025,
    projected_workforce = projected_2029,
    percent_change = percent_change,
    annual_entrants = annual_entrants,
    avg_annual_retirements = avg_annual_retirements,
    avg_retirement_rate = annual_retirement_rate
  )

cat(sprintf("  ✓ Loaded %d subspecialties\n", nrow(baseline_data)))
cat("\n")

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Run Projections for Each Scenario
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

cat("Running projections with varied retirement rates...\n\n")

all_results <- list()

for (scenario_id in names(retirement_scenarios)) {
  scenario <- retirement_scenarios[[scenario_id]]

  cat(sprintf("[%s] %s\n", scenario_id, scenario$name))

  # Adjust retirement rates
  # The 'mutate' function adds new variables to a tibble.
  adjusted_rates <- BASELINE_RATES %>%
    mutate(
      adjusted_rate = baseline_rate * (1 + scenario$adjustment),
      adjusted_rate = pmax(adjusted_rate, baseline_rate * 0.1),  # Min 10% of baseline
      adjusted_rate = pmin(adjusted_rate, baseline_rate * 10)    # Max 10x baseline
    )

  # Calculate projections with adjusted retirement rates
  results <- baseline_data %>%
    # The 'left_join' function joins two tibbles based on a common variable.
    left_join(adjusted_rates, by = c("subspecialty" = "subspecialty")) %>%
    mutate(
      # Use original retirements as anchor, then apply adjustment to stay consistent with baseline
      avg_annual_retirements = avg_annual_retirements * (adjusted_rate / baseline_rate),

      # Keep SSOT fellowship numbers (no override from outdated config)
      annual_entrants = annual_entrants,

      # Recalculate replacement ratio
      replacement_ratio = annual_entrants / avg_annual_retirements,

      # Recalculate projected workforce
      projected_workforce = baseline_workforce - (4 * avg_annual_retirements) + (4 * annual_entrants),

      # Calculate percent change
      percent_change = 100 * (projected_workforce - baseline_workforce) / baseline_workforce,

      # Add scenario identifier
      scenario_id = scenario_id,
      scenario_name = scenario$name,
      retirement_adjustment = scenario$adjustment
    )

  all_results[[scenario_id]] <- results

  cat(sprintf("  Adjusted rates: URPS %.4f, GO %.4f, MIGS %.4f\n",
              adjusted_rates$adjusted_rate[adjusted_rates$subspecialty == "URPS"],
              adjusted_rates$adjusted_rate[adjusted_rates$subspecialty == "GO"],
              adjusted_rates$adjusted_rate[adjusted_rates$subspecialty == "MIGS"]))
  cat(sprintf("  ✓ Completed\n"))
}

cat("\n")

# The 'bind_rows' function combines data frames by row.
# Combine all results
comparison_data <- bind_rows(all_results)

# Save comparison data
output_file <- here("data/retirement_sensitivity.csv")
# The 'write_csv' function writes a tibble to a CSV file.
write_csv(comparison_data, output_file)
cat(sprintf("✓ Saved comparison data: %s\n\n", output_file))

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Create Comparison Table
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

cat(paste0(rep("=", 80), collapse = ""), "\n")
cat("RETIREMENT SENSITIVITY: Projected 2029 Workforce\n")
cat(paste0(rep("=", 80), collapse = ""), "\n")
cat("\n")

# Summary table
# The 'select' function keeps or drops variables from a tibble.
summary_table <- comparison_data %>%
  select(scenario_name, subspecialty, baseline_workforce,
         adjusted_rate, projected_workforce, percent_change) %>%
  # The 'arrange' function reorders rows.
  arrange(subspecialty, desc(adjusted_rate)) %>%
  mutate(
    baseline_workforce = format(round(baseline_workforce), big.mark = ","),
    adjusted_rate = sprintf("%.2f%%", adjusted_rate),
    projected_workforce = format(round(projected_workforce), big.mark = ","),
    percent_change = sprintf("%.1f%%", percent_change)
  )

# Print by subspecialty
for (subspec in c("URPS", "GO", "MIGS")) {
  cat(sprintf("\n%s:\n", subspec))
  # The 'filter' function selects rows based on their values.
  subspec_table <- summary_table %>%
    filter(subspecialty == subspec) %>%
    select(Scenario = scenario_name,
           Baseline = baseline_workforce,
           `Retirement Rate` = adjusted_rate,
           `Projected 2029` = projected_workforce,
           `Change` = percent_change)

  print(subspec_table, width = Inf)
}

cat("\n")

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Aggregate Summary
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

aggregate_summary <- comparison_data %>%
  # The 'group_by' function groups a tibble by one or more variables.
  group_by(scenario_id, scenario_name, retirement_adjustment) %>%
  # The 'summarise' function creates a new tibble with summary statistics.
  summarise(
    total_2029 = sum(projected_workforce),
    total_baseline = sum(baseline_workforce),
    net_change = total_2029 - total_baseline,
    pct_change = 100 * net_change / total_baseline,
    .groups = "drop"
  ) %>%
  arrange(desc(total_2029))

cat(paste0(rep("=", 80), collapse = ""), "\n")
cat("AGGREGATE SUMMARY: Total Workforce Across All Subspecialties\n")
cat(paste0(rep("=", 80), collapse = ""), "\n")
cat("\n")

aggregate_display <- aggregate_summary %>%
  # The 'transmute' function is similar to 'mutate', but it drops all other variables.
  transmute(
    Scenario = scenario_name,
    `Retirement Adjustment` = sprintf("%+.0f%%", retirement_adjustment * 100),
    `2029 Total` = format(round(total_2029), big.mark = ","),
    `Net Change` = sprintf("%+.0f", net_change),
    `% Change` = sprintf("%.1f%%", pct_change)
  )

print(aggregate_display, width = Inf)

cat("\n")

# Range analysis
# The 'slice_max' function selects the row with the maximum value for a given variable.
best_case <- aggregate_summary %>% slice_max(total_2029, n = 1)
# The 'slice_min' function selects the row with the minimum value for a given variable.
worst_case <- aggregate_summary %>% slice_min(total_2029, n = 1)
# The 'filter' function selects rows based on their values.
baseline_case <- aggregate_summary %>% filter(scenario_id == "baseline")

cat("Sensitivity Range:\n")
cat(sprintf("  • Best case (%s): %s physicians (%+.0f from baseline)\n",
            best_case$scenario_name,
            format(round(best_case$total_2029), big.mark = ","),
            best_case$total_2029 - baseline_case$total_2029))
cat(sprintf("  • Baseline: %s physicians\n",
            format(round(baseline_case$total_2029), big.mark = ",")))
cat(sprintf("  • Worst case (%s): %s physicians (%+.0f from baseline)\n",
            worst_case$scenario_name,
            format(round(worst_case$total_2029), big.mark = ","),
            worst_case$total_2029 - baseline_case$total_2029))
cat(sprintf("  • Total range: %s physicians (%.1f%%)\n",
            format(round(best_case$total_2029 - worst_case$total_2029), big.mark = ","),
            100 * (best_case$total_2029 - worst_case$total_2029) / baseline_case$total_2029))

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Create Visualization
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

cat("\n[", as.character(Sys.time()), "] Creating retirement sensitivity figures\n", sep = "")

# Define scenario order for plotting
scenario_order <- c(
  "aggressive_lower", "conservative_lower", "threshold_plus_1yr",
  "baseline",
  "threshold_minus_1yr", "conservative_higher", "aggressive_higher"
)

plot_data <- comparison_data %>%
  filter(scenario_id %in% scenario_order) %>%
  mutate(
    scenario_id = factor(scenario_id, levels = scenario_order),
    subspecialty_label = case_when(
      subspecialty == "URPS" ~ "Urogynecology (URPS)",
      subspecialty == "GO" ~ "Gynecologic Oncology",
      subspecialty == "MIGS" ~ "MIGS",
      TRUE ~ subspecialty
    ),
    # Shorten scenario names for plotting
    scenario_short = case_when(
      scenario_id == "aggressive_lower" ~ "Aggr. Lower\n(-30%)",
      scenario_id == "conservative_lower" ~ "Cons. Lower\n(-10%)",
      scenario_id == "threshold_plus_1yr" ~ "Threshold\n+1yr (-15%)",
      scenario_id == "baseline" ~ "Baseline\n(0%)",
      scenario_id == "threshold_minus_1yr" ~ "Threshold\n-1yr (+15%)",
      scenario_id == "conservative_higher" ~ "Cons. Higher\n(+10%)",
      scenario_id == "aggressive_higher" ~ "Aggr. Higher\n(+30%)",
      TRUE ~ scenario_name
    ),
    scenario_short = factor(scenario_short,
                            levels = unique(scenario_short[order(scenario_id)]))
  )

# The 'ggplot' function initializes a ggplot object.
# Figure 1: Workforce projections by retirement scenario
fig1 <- ggplot(plot_data,
               aes(x = scenario_short, y = projected_workforce,
                   fill = subspecialty_label)) +
  # The 'geom_col' function creates a column plot.
  geom_col(position = position_dodge(width = 0.85), width = 0.75) +
  # The 'geom_hline' function adds a horizontal line to the plot.
  geom_hline(data = plot_data %>%
               filter(scenario_id == "baseline") %>%
               group_by(subspecialty_label) %>%
               summarise(baseline = first(baseline_workforce), .groups = "drop"),
             aes(yintercept = baseline, color = subspecialty_label),
             linetype = "dashed", linewidth = 0.6, show.legend = FALSE) +

  # The 'scale_fill_viridis_d' function provides a set of colorblind-friendly colors.
  scale_fill_viridis_d(option = "plasma", begin = 0.2, end = 0.8) +
  # The 'scale_color_viridis_d' function provides a set of colorblind-friendly colors.
  scale_color_viridis_d(option = "plasma", begin = 0.2, end = 0.8) +
  # The 'scale_y_continuous' function sets the y-axis limits and breaks.
  scale_y_continuous(labels = comma, expand = expansion(mult = c(0.05, 0.1))) +

  # The 'labs' function sets the plot labels.
  labs(
    title = "Retirement Threshold Sensitivity Analysis",
    subtitle = "Impact of varying retirement detection thresholds on 2029 workforce projections\nDashed lines show 2025 baseline",
    x = "Retirement Rate Adjustment",
    y = "Projected Active Physicians (2029)",
    fill = "Subspecialty"
  ) +

  # The 'theme_minimal' function sets the plot theme.
  theme_minimal(base_size = 11) +
  # The 'theme' function modifies the plot theme.
  theme(
    plot.title = element_text(face = "bold", size = 14),
    plot.subtitle = element_text(color = "gray40", size = 10),
    axis.text.x = element_text(size = 9, lineheight = 0.9),
    legend.position = "bottom",
    legend.title = element_text(face = "bold"),
    panel.grid.major.x = element_blank(),
    panel.grid.minor = element_blank()
  )

# The 'ggsave' function saves a ggplot object to a file.
ggsave(here("figures/retirement_sensitivity_workforce.png"),
       fig1, width = 12, height = 7, dpi = 600, bg = "white")
cat("  Saved: cliff/figures/retirement_sensitivity_workforce.png\n")

ggsave(here("figures/retirement_sensitivity_workforce.tiff"),
       fig1, width = 12, height = 7, dpi = 600, bg = "white",
       compression = "lzw")
cat("  Saved: cliff/figures/retirement_sensitivity_workforce.tiff\n")

# Figure 2: Percent change by scenario
# The 'ggplot' function initializes a ggplot object.
fig2 <- ggplot(plot_data,
               aes(x = scenario_short, y = percent_change,
                   group = subspecialty_label, color = subspecialty_label)) +
  # The 'geom_line' function creates a line plot.
  geom_line(linewidth = 1.3) +
  # The 'geom_point' function creates a scatter plot.
  geom_point(size = 3.5) +
  # The 'geom_hline' function adds a horizontal line to the plot.
  geom_hline(yintercept = 0, linetype = "dashed", color = "gray50") +

  # The 'scale_color_viridis_d' function provides a set of colorblind-friendly colors.
  scale_color_viridis_d(option = "plasma", begin = 0.2, end = 0.8) +
  # The 'scale_y_continuous' function sets the y-axis limits and breaks.
  # The 'label_percent' function formats numbers as percentages.
  scale_y_continuous(labels = label_percent(scale = 1),
                      expand = expansion(mult = c(0.15, 0.15))) +

  # The 'labs' function sets the plot labels.
  labs(
    title = "Workforce Change Sensitivity to Retirement Rates",
    subtitle = "Percent change in workforce (2025 → 2029) under different retirement rate assumptions",
    x = "Retirement Rate Adjustment",
    y = "Percent Change in Workforce",
    color = "Subspecialty"
  ) +

  # The 'theme_minimal' function sets the plot theme.
  theme_minimal(base_size = 11) +
  # The 'theme' function modifies the plot theme.
  theme(
    plot.title = element_text(face = "bold", size = 14),
    plot.subtitle = element_text(color = "gray40", size = 10),
    axis.text.x = element_text(size = 9, lineheight = 0.9),
    legend.position = "bottom",
    legend.title = element_text(face = "bold"),
    panel.grid.minor = element_blank()
  )

# The 'ggsave' function saves a ggplot object to a file.
ggsave(here("figures/retirement_sensitivity_change.png"),
       fig2, width = 10, height = 7, dpi = 600, bg = "white")
cat("  Saved: cliff/figures/retirement_sensitivity_change.png\n")

ggsave(here("figures/retirement_sensitivity_change.tiff"),
       fig2, width = 10, height = 7, dpi = 600, bg = "white",
       compression = "lzw")
cat("  Saved: cliff/figures/retirement_sensitivity_change.tiff\n")

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Manuscript Text
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

cat("\n")
cat(paste0(rep("=", 80), collapse = ""), "\n")
cat("INTERPRETATION FOR MANUSCRIPT\n")
cat(paste0(rep("=", 80), collapse = ""), "\n")
cat("\n")

cat("Suggested Results Text:\n\n")
cat(paste0(rep("-", 80), collapse = ""), "\n")

total_range <- best_case$total_2029 - worst_case$total_2029
pct_range <- 100 * total_range / baseline_case$total_2029

cat(sprintf("\"Sensitivity analysis varying retirement detection thresholds by ±1 year\n"))
cat(sprintf("(approximating ±15%% change in retirement rates) demonstrated that projected\n"))
cat(sprintf("workforce estimates remained directionally consistent. Under the most\n"))
cat(sprintf("conservative scenario (extending detection threshold +1 year), total 2029\n"))
cat(sprintf("workforce was %s physicians. Under the most aggressive scenario (shortening\n",
            format(round(best_case$total_2029), big.mark = ",")))
cat(sprintf("threshold -1 year), total 2029 workforce was %s physicians. This represents\n",
            format(round(worst_case$total_2029), big.mark = ",")))
cat(sprintf("a range of %s physicians (%.1f%% of baseline), confirming that relative\n",
            format(round(total_range), big.mark = ","), pct_range))
cat(sprintf("differences between subspecialties persisted across retirement rate\n"))
cat(sprintf("assumptions.\"\n"))

cat(paste0(rep("-", 80), collapse = ""), "\n")

cat("\n")
cat(paste0(rep("=", 80), collapse = ""), "\n")
cat("\n")

if (!interactive()) {
  cat("[", as.character(Sys.time()), "] Script completed successfully\n", sep = "")
}
