#!/usr/bin/env Rscript
# =============================================================================
# URPS / FPMRS taxonomy findability — Euler diagram
# =============================================================================
#
# Purpose:
#   Create an ENT-style polished Euler diagram showing how the identifiable
#   urogynecology workforce shrinks as NPPES taxonomy rules become stricter.
#
# Output:
#   manuscript/figures/urps_taxonomy_euler.png
#   manuscript/figures/urps_taxonomy_euler.tiff
# =============================================================================

suppressPackageStartupMessages({
  library(eulerr)
  library(grid)
  library(here)
})

output_dir <- here::here("manuscript", "figures")
if (!dir.exists(output_dir)) dir.create(output_dir, recursive = TRUE)

output_png <- file.path(output_dir, "urps_taxonomy_euler.png")
output_tiff <- file.path(output_dir, "urps_taxonomy_euler.tiff")

# Source counts from Tyler Muffly summary email / CMS draft support note
n_board_total <- 1172L
n_found_in_nppes <- 1152L
n_tax_any <- 600L
n_tax_primary <- 207L

n_board_only <- n_board_total - n_tax_any                 # 572
n_any_not_primary <- n_tax_any - n_tax_primary            # 393
n_not_in_nppes <- n_board_total - n_found_in_nppes        # 20
n_no_fpmrs_taxonomy <- n_found_in_nppes - n_tax_any       # 552

zones <- c(
  "Board" = n_board_only,
  "Board&AnySlot" = n_any_not_primary,
  "Board&AnySlot&Primary" = n_tax_primary
)

fit <- eulerr::euler(zones, shape = "ellipse")

board_fill <- "#214E72"
any_fill <- "#F4B942"
primary_fill <- "#D1495B"
text_dark <- "#183247"
text_dim <- "#56738A"

.fmt <- function(x) format(x, big.mark = ",")
.pct <- function(x, denom) sprintf("%.1f%%", 100 * x / denom)

euler_plot <- plot(
  fit,
  fills = list(
    fill = c(board_fill, any_fill, primary_fill),
    alpha = c(0.22, 0.52, 0.88)
  ),
  edges = list(
    col = c(board_fill, any_fill, primary_fill),
    lwd = 2.4
  ),
  labels = FALSE,
  legend = FALSE
)

title_text <- "Most board-certified urogynecologists are invisible to primary NPPES taxonomy"
subtitle_text <- sprintf(
  paste(
    "%s ABOG-certified FPMRS physicians had NPIs.",
    "%s were detectable with 207VF0040X anywhere in NPPES.",
    "%s used it as their primary taxonomy."
  ),
  .fmt(n_board_total),
  .fmt(n_tax_any),
  .fmt(n_tax_primary)
)

footnote_lines <- c(
  sprintf(
    "Not captured by 207VF0040X taxonomy: %s physicians (%s). Includes %s found in NPPES without the code and %s not found in the analyzed NPPES file.",
    .fmt(n_board_only),
    .pct(n_board_only, n_board_total),
    .fmt(n_no_fpmrs_taxonomy),
    .fmt(n_not_in_nppes)
  ),
  "Source: Tyler Muffly summary comparing ABOG board certification with NPPES taxonomy slots 1-5. Figure generated by scripts/create_urps_taxonomy_euler.R."
)

draw_figure <- function(device = c("png", "tiff")) {
  device <- match.arg(device)
  if (device == "png") {
    png(output_png, width = 15, height = 10, units = "in", res = 300, bg = "white")
  } else {
    tiff(output_tiff, width = 15, height = 10, units = "in", res = 300, bg = "white")
  }

  grid::grid.newpage()
  grid::pushViewport(grid::viewport(layout = grid::grid.layout(
    nrow = 4, ncol = 1,
    heights = grid::unit(c(0.8, 0.45, 7.85, 0.9), "in")
  )))

  grid::pushViewport(grid::viewport(layout.pos.row = 1))
  grid::grid.text(
    title_text,
    x = unit(0.5, "npc"),
    y = unit(0.45, "npc"),
    gp = grid::gpar(fontsize = 22, fontface = "bold", col = text_dark)
  )
  grid::popViewport()

  grid::pushViewport(grid::viewport(layout.pos.row = 2))
  grid::grid.text(
    subtitle_text,
    x = unit(0.5, "npc"),
    y = unit(0.55, "npc"),
    gp = grid::gpar(fontsize = 12, col = text_dim, fontface = "italic")
  )
  grid::popViewport()

  grid::pushViewport(grid::viewport(layout.pos.row = 3))
  print(euler_plot, newpage = FALSE)

  grid::grid.text(
    sprintf(
      "ABOG-certified FPMRS\nn = %s",
      .fmt(n_board_total)
    ),
    x = unit(0.56, "npc"),
    y = unit(0.84, "npc"),
    gp = grid::gpar(fontsize = 14, fontface = "bold", col = board_fill)
  )

  grid::grid.text(
    sprintf(
      "Detected by 207VF0040X\nin any NPPES slot\nn = %s",
      .fmt(n_tax_any)
    ),
    x = unit(0.83, "npc"),
    y = unit(0.60, "npc"),
    gp = grid::gpar(fontsize = 13, fontface = "bold", col = "#C98200")
  )

  grid::grid.segments(
    x0 = unit(0.79, "npc"), y0 = unit(0.59, "npc"),
    x1 = unit(0.73, "npc"), y1 = unit(0.56, "npc"),
    gp = grid::gpar(col = "#C98200", lwd = 1.5)
  )

  grid::grid.text(
    sprintf(
      "Detected by\nprimary taxonomy only\nn = %s",
      .fmt(n_tax_primary)
    ),
    x = unit(0.59, "npc"),
    y = unit(0.47, "npc"),
    gp = grid::gpar(fontsize = 14, fontface = "bold", col = "#B0223B")
  )

  grid::grid.text(
    sprintf(
      "Not captured by\nFPMRS taxonomy\nn = %s",
      .fmt(n_board_only)
    ),
    x = unit(0.30, "npc"),
    y = unit(0.44, "npc"),
    gp = grid::gpar(fontsize = 13, fontface = "bold", col = text_dark)
  )
  grid::grid.segments(
    x0 = unit(0.36, "npc"), y0 = unit(0.44, "npc"),
    x1 = unit(0.42, "npc"), y1 = unit(0.45, "npc"),
    gp = grid::gpar(col = text_dark, lwd = 1.5)
  )

  grid::grid.text(
    sprintf("+%s beyond primary", .fmt(n_any_not_primary)),
    x = unit(0.67, "npc"),
    y = unit(0.73, "npc"),
    gp = grid::gpar(fontsize = 12.5, fontface = "bold", col = "#7A5200")
  )
  grid::popViewport()

  grid::pushViewport(grid::viewport(layout.pos.row = 4))
  y_positions <- c(0.68, 0.18)
  for (i in seq_along(footnote_lines)) {
    grid::grid.text(
      footnote_lines[i],
      x = unit(0.02, "npc"),
      y = unit(y_positions[i], "npc"),
      hjust = 0,
      gp = grid::gpar(
        fontsize = 9,
        col = text_dim,
        fontface = if (i == 2) "italic" else "plain"
      )
    )
  }
  grid::popViewport()

  dev.off()
}

draw_figure("png")
draw_figure("tiff")

png_size <- file.size(output_png)
tiff_size <- file.size(output_tiff)

if (!file.exists(output_png) || is.na(png_size) || png_size == 0L) {
  stop("PNG output missing or empty: ", output_png, call. = FALSE)
}
if (!file.exists(output_tiff) || is.na(tiff_size) || tiff_size == 0L) {
  stop("TIFF output missing or empty: ", output_tiff, call. = FALSE)
}

cat(sprintf("Saved PNG : %s (%.1f KB)\n", output_png, png_size / 1024))
cat(sprintf("Saved TIFF: %s (%.1f MB)\n", output_tiff, tiff_size / (1024^2)))
