#!/usr/bin/env Rscript
source(here::here("R", "wc_path.R"))
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# TIER-3: EXTERNAL validation of the clinical-practice DEPARTURE classifier
# against an INDEPENDENT state-medical-board reference standard.
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# THE CLASSIFIER (test): the manuscript's multi-source consensus assigns each
# physician is_retired_for_cohorting (departed vs active) and a retirement_year,
# from six Medicare/NPPES/ABMS administrative signals.
#
# THE REFERENCE (gold standard): state medical-board LICENSE lifecycle, from
# ~40 state licensing authorities (data/state_licenses/state_board_lifecycle_registry.csv
# in the sibling isochrones repo). License status is generated by state boards,
# NOT by Medicare billing, NPPES, or ABMS certification, so it is INDEPENDENT of
# every signal the classifier uses.
#
# Per-NPI reference label (a physician active-licensed in ANY state has not
# departed; deceased is terminal and overrides a stale active license):
#   deceased           -> DEPARTED (definitive)
#   any active license -> ACTIVE
#   retired/revoked/surrendered/suspended (no active license) -> DEPARTED (definitive)
#   inactive-only      -> AMBIGUOUS (weak; a physician may be inactive in one
#                         state while practicing in another) -> held out of the
#                         primary confusion matrix, reported separately.
#
# CAVEATS (reported, not hidden): (1) a license reference is imperfect truth (an
# active license need not mean active practice, and vice versa), so metrics are
# "agreement with an independent administrative standard," not against ground
# truth; (2) coverage is partial (only NPIs the boards report); (3) the reference
# retirement_year is board-derived here (no federal backfill), so timing
# independence is preserved.
#
# OUTPUT: data/classifier_validation_external.csv (metrics, overall + by
#         subspecialty) and a console report.
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

suppressPackageStartupMessages({library(readr); library(dplyr); library(tidyr); library(here)})

COHORT <- wc_path("cohort_csv")
REG    <- wc_path("state_registry")
stopifnot(file.exists(COHORT), file.exists(REG))

SUBS <- c(URPS="Female Pelvic Medicine & Reconstructive Surgery",
          GO="Gynecologic Oncology", MIGS="MIGS")

# ---- test: classifier labels for the 3 surgical subspecialties -------------
coh <- read_csv(COHORT, show_col_types=FALSE, guess_max=1e5) %>%
  filter(subspecialty %in% unname(SUBS)) %>%
  transmute(npi=as.character(npi),
            subspec=names(SUBS)[match(subspecialty,SUBS)],
            test_departed=as.logical(is_retired_for_cohorting),
            test_year=suppressWarnings(as.integer(retirement_year))) %>%
  distinct(npi,.keep_all=TRUE) %>% filter(!is.na(subspec), !is.na(test_departed))

# ---- reference: collapse registry to one INDEPENDENT label per NPI ---------
reg <- read_csv(REG, show_col_types=FALSE, guess_max=1e5) %>%
  transmute(npi=as.character(npi), lifecycle_state=tolower(lifecycle_state),
            ref_year=suppressWarnings(as.integer(retirement_year)))
DEFINITIVE <- c("retired","revoked","surrendered","suspended")
ref <- reg %>% group_by(npi) %>% summarise(
    any_deceased = any(lifecycle_state=="deceased"),
    any_active   = any(lifecycle_state=="active"),
    any_defexit  = any(lifecycle_state %in% DEFINITIVE),
    any_inactive = any(lifecycle_state=="inactive"),
    # earliest board-dated exit year (deceased/definitive rows), if any
    ref_year = suppressWarnings(min(ref_year[lifecycle_state %in% c("deceased",DEFINITIVE)], na.rm=TRUE)),
    .groups="drop") %>%
  mutate(ref_year = ifelse(is.finite(ref_year), ref_year, NA_integer_),
         ref_label = case_when(
           any_deceased ~ "departed",
           any_active   ~ "active",
           any_defexit  ~ "departed",
           any_inactive ~ "ambiguous",
           TRUE         ~ "ambiguous"),
         ref_departed = ref_label=="departed")

m <- coh %>% left_join(ref, by="npi")

# ---- coverage --------------------------------------------------------------
cat("=== COVERAGE ===\n")
cov <- m %>% mutate(matched = !is.na(ref_label)) %>%
  group_by(subspec) %>% summarise(
    n_cohort=n(), matched=sum(matched),
    ref_active=sum(ref_label=="active",na.rm=TRUE),
    ref_departed=sum(ref_label=="departed",na.rm=TRUE),
    ref_ambiguous=sum(ref_label=="ambiguous",na.rm=TRUE), .groups="drop")
cov_tot <- cov %>% summarise(subspec="ALL", across(where(is.numeric), sum))
cov_all <- bind_rows(cov, cov_tot) %>% mutate(pct_matched=round(100*matched/n_cohort,1),
    pct_labelled=round(100*(ref_active+ref_departed)/n_cohort,1))
print(as.data.frame(cov_all), row.names=FALSE)

# ---- confusion matrix + metrics (primary: active vs departed) --------------
metrics <- function(df){
  d <- df %>% filter(ref_label %in% c("active","departed"))
  TP <- sum(d$ref_departed & d$test_departed)
  FN <- sum(d$ref_departed & !d$test_departed)
  FP <- sum(!d$ref_departed & d$test_departed)
  TN <- sum(!d$ref_departed & !d$test_departed)
  n <- TP+FN+FP+TN
  sens <- TP/(TP+FN); spec <- TN/(TN+FP)
  ppv <- TP/(TP+FP); npv <- TN/(TN+FN); acc <- (TP+TN)/n
  # Cohen's kappa
  po <- acc; pe <- ((TP+FP)*(TP+FN) + (FN+TN)*(FP+TN))/n^2
  kappa <- (po-pe)/(1-pe)
  data.frame(n=n, TP=TP, FN=FN, FP=FP, TN=TN,
             sensitivity=round(sens,3), specificity=round(spec,3),
             ppv=round(ppv,3), npv=round(npv,3), accuracy=round(acc,3),
             kappa=round(kappa,3))
}
cat("\n=== CONFUSION-MATRIX METRICS (reference: state-board license lifecycle) ===\n")
cat("(active vs definitive-exit; inactive-only rows excluded)\n")
by_sub <- lapply(names(SUBS), function(k){ x<-metrics(m %>% filter(subspec==k)); x$subspec<-k; x })
allm <- metrics(m); allm$subspec<-"ALL"
mtab <- bind_rows(c(by_sub, list(allm)))[,c("subspec","n","TP","FN","FP","TN",
        "sensitivity","specificity","ppv","npv","accuracy","kappa")]
print(as.data.frame(mtab), row.names=FALSE)

# ---- sensitivity: treat inactive-only as departed (upper bound on exits) ----
m2 <- m %>% mutate(ref_label=ifelse(ref_label=="ambiguous" & any_inactive,"departed",ref_label),
                   ref_departed=ref_label=="departed")
cat("\n=== SENSITIVITY: counting weak 'inactive-only' licenses as departed ===\n")
print(as.data.frame({x<-metrics(m2);x$subspec<-"ALL";x[,c("subspec","n","sensitivity","specificity","ppv","npv","kappa")]}), row.names=FALSE)

# ---- timing agreement (both flag departed AND both have a year) ------------
cat("\n=== TIMING AGREEMENT (classifier year vs board year, both departed) ===\n")
tim <- m %>% filter(ref_departed, test_departed, !is.na(ref_year), !is.na(test_year)) %>%
  mutate(diff = test_year - ref_year, absdiff=abs(diff))
timing <- function(d) if(nrow(d)==0) NULL else data.frame(
  n=nrow(d), mean_diff=round(mean(d$diff),2), median_absdiff=median(d$absdiff),
  mae=round(mean(d$absdiff),2), within1=round(100*mean(d$absdiff<=1),1),
  within2=round(100*mean(d$absdiff<=2),1))
tt <- lapply(names(SUBS), function(k){x<-timing(tim %>% filter(subspec==k)); if(!is.null(x)) x$subspec<-k; x})
ta <- timing(tim); if(!is.null(ta)) ta$subspec<-"ALL"
timtab <- bind_rows(c(tt,list(ta)))
if(nrow(timtab)) print(as.data.frame(timtab[,c("subspec","n","mean_diff","median_absdiff","mae","within1","within2")]), row.names=FALSE)

# ---- persist ---------------------------------------------------------------
out <- mtab %>% mutate(reference="state_board_lifecycle_registry",
                       label_rule="active_vs_definitive_exit_inactive_excluded")
write_csv(out, here::here("data","classifier_validation_external.csv"))
cat("\nWrote data/classifier_validation_external.csv\n")
cat("\nReference standard: independent state medical-board license lifecycle (",
    format(nrow(distinct(reg,npi)), big.mark=","), " NPIs). ",
    "License status is not derived from Medicare/NPPES/ABMS.\n", sep="")
